name: CI build

on: [pull_request, workflow_dispatch, push]
jobs:
  go16:
    runs-on: ubuntu-latest
    container: ghcr.io/pinpoint-apm/pinpoint-c-agent/golang-build-env-1.16:latest
    steps:
      - uses: actions/checkout@v2
      - name: test asm-c
        run: |
          cd asm && mkdir build && cd build && cmake .. && make
          ctest -T Test
      - name: test asm-go
        run: |
          cd asm
          go test -v  .
      - name: api test
        run: |
          cd common
          go test -v  .
      - name: aop test
        run: |
          cd aop
          go test -v  .

  updatelibs:
    runs-on: ubuntu-latest
    needs: go16
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: "1.16"
      - name: update go mod under libs
        run: |
          cd libs
          for dir in * ; do cd  $dir; go get github.com/pinpoint-apm/go-aop-agent@${{ github.sha }}; cd ..; done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update libs module to the latest commit
          file_pattern: libs/*.mod libs/*.sum
          create_branch: true
          branch: style-update-common-${{ github.sha }}

  go13:
    runs-on: ubuntu-latest
    container: ghcr.io/pinpoint-apm/pinpoint-c-agent/golang-build-env-1.13:latest
    steps:
      - uses: actions/checkout@v2
      - name: test asm-c
        run: |
          cd asm && mkdir build && cd build && cmake ..
          make
          ctest -T Test
          ctest -T Coverage
      - name: test asm-go
        run: |
          cd asm
          go test -v -coverprofile cover.out .
      - name: api test
        run: |
          cd common
          go test -v -coverprofile cover.out .
      - name: aop test
        run: |
          cd aop
          go test -v -coverprofile cover.out .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
