name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pinpoint-apm/pinpoint-c-agent/golang-build-env-1.16:latest
    steps:
      - uses: actions/checkout@v2
      - name: test -NTEST
        run : |
          cd aop
          make
          ./test
      - name: api test
        run: |
          cd common
          go test -v -coverprofile cover.out .
          cd ../aop
          go test -v -v -coverprofile cover.out .
      - name: Codecovage
        uses: codecov/codecov-action@v1

      - name: build mux
        run: |
          cd testapps/mux
          GOOS=linux GOARCH=amd64 go mod download
          GOOS=linux GOARCH=amd64 go build -o testapp
      - name: build echo
        run: |
          cd testapps/echo
          GOOS=linux GOARCH=amd64 go mod download
          GOOS=linux GOARCH=amd64 go build -o testapp
